import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Message: NextPage = () => {
  const messages = api.listings.getMessage.useQuery();
  const user = useUser();

  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="mt-5 flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-4">
        <h1 className="mt-5 text-4xl font-bold text-white">Messages</h1>
        <div className="mb-5 mt-5 h-[1px] w-1/2 bg-gray-500"></div>
        <div className="container mx-auto flex w-full flex-col text-white md:w-[600px]">
          {user.isSignedIn && (
            <>
              <div className="mt-10 flex w-full flex-col gap-3 md:w-full">
                {messages.data?.map((message) => (
                  <div
                    className="m-2 rounded bg-slate-600 p-5"
                    key={message.id}
                  >
                    {message.message}
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default Message;
