import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { api } from "~/utils/api";

type SellItemForm = {
  name: string;
  description: string;
  price: string;
};

const SellAnItem: NextPage = () => {
  const createListing = api.listings.create.useMutation();
  const router = useRouter();
  const { register, handleSubmit } = useForm<SellItemForm>();
  const onSubmit = (formData: SellItemForm) => {
    createListing
      .mutateAsync({
        ...formData,
        price: parseFloat(formData.price),
      })
      .then(() => {
        router.push("/");
      });
  };
  return (
    <>
      <Head>
        <title>Sell an Item - Online Market Place</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-10 mt-20 text-4xl font-semibold text-white">
          Sell an Item
        </h1>
        <div className="container flex   items-center justify-center gap-12 px-4 py-4 ">
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="flex w-full flex-col gap-3 md:w-1/3"
          >
            <input
              placeholder="Name"
              className="w-full rounded-md px-4 py-2 outline-none focus:outline-none"
              {...register("name", { required: true })}
            />
            <textarea
              placeholder="Description"
              className="w-full rounded-md px-4 py-2 outline-none focus:outline-none"
              {...register("description", { required: true })}
            />
            <input
              placeholder="Price"
              className="w-full rounded-md px-4 py-2 outline-none focus:outline-none"
              type="number"
              step="0.01"
              {...register("price", { required: true })}
            />
            <input
              className="mt-6 w-full cursor-pointer rounded-md bg-neutral-300 py-2 text-black hover:bg-slate-900 hover:text-white"
              type="submit"
            />
          </form>
        </div>
      </main>
    </>
  );
};

export default SellAnItem;
