import { SignUp } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useForm } from "react-hook-form";

type SellItemForm = {
  name: string;
  description: string;
  price: number;
};

const Register: NextPage = () => {
  const { register, handleSubmit } = useForm<SellItemForm>();
  const onSubmit = (formData: SellItemForm) => console.log(formData);
  return (
    <>
      <Head>
        <title>Sell an Item - Online Market Place</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="mb-5 mt-5 text-3xl font-semibold text-white">Sign Up</h1>
        <SignUp />
      </main>
    </>
  );
};

export default Register;
